### ISSUE TITLE
Detect plans for NC vs. Null Island, and use the correct precinct geographies.

### ISSUE THREAD

**Issue by migurski** [migurski/PlanScore#21]

**Comment by migurski** [comment]
Home stretch for this issue; observed this bug in NC:

```
unsupported operand type(s) for *: 'float' and 'NoneType': TypeError
Traceback (most recent call last):
File "/var/task/planscore/districts.py", line 71, in lambda_handler
for _ in consume_tiles(storage, partial):
File "/var/task/planscore/districts.py", line 138, in consume_tiles
score_precinct(partial, precinct)
File "/var/task/planscore/districts.py", line 159, in score_precinct
precinct_value = precinct_fraction * precinct['properties'][name]
```
